chat/apps/guilds/urls.py
from django.urls import path

from .features.channels.urls import urlpatterns as channels_routes
from .features.invites.urls import urlpatterns as invites_routes
from .views import (
    GuildCreateView,
    GuildDetailView,
    GuildHomeView,
    GuildInvitesView,
    GuildJoinView,
    GuildSettingsChannelsView,
    GuildSettingsHomeView,
    GuildSettingsMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path("join/", view=GuildJoinView.as_view(), name="join"),
]

# Guild routes
urlpatterns += [
    path(
        "<uuid:guild_id>/",
        view=GuildDetailView.as_view(),
        name="guild_details",
    ),
    path(
        "<uuid:guild_id>/invites/",
        view=GuildInvitesView.as_view(),
        name="guild_invites",
    ),
    path(
        "<uuid:guild_id>/settings/",
        view=GuildSettingsHomeView.as_view(),
        name="guild_settings",
    ),
    path(
        "<uuid:guild_id>/settings/members/",
        view=GuildSettingsMembersView.as_view(),
        name="guild_settings_members",
    ),
    path(
        "<uuid:guild_id>/settings/channels/",
        view=GuildSettingsChannelsView.as_view(),
        name="guild_settings_channels",
    ),
]

# Channel routes
urlpatterns += channels_routes

# Invite routes
urlpatterns += invites_routes

chat/guild/urls.py
from django.urls import path

from .views import (
    GuildHomeView,
    GuildDetailView,
    GuildCreateView,
    GuildInviteView,
    GuildDeleteInviteView,
    GuildMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path(
        "<int:guild_id>/invite/", view=GuildInviteView.as_view(), name="invite"
    ),
    path(
        "<uuid:guild_id>/members/",
        view=GuildMembersView.as_view(),
        name="members",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>",
        view=GuildInviteView.as_view(),
        name="invite_join",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>/delete",
        view=GuildDeleteInviteView.as_view(),
        name="invite_delete",
    ),
    path("<uuid:guild_id>/", view=GuildDetailView.as_view(), name="detail"),
]

chat/pages/urls.py
from django.urls import path

from chat.pages.views import HomeView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
]

chat/users/urls.py
from django.urls import path

from chat.users.views import (
    UserClientUpdateView,
    UserDetailView,
    UserFistConnectView,
    UserRedirectView,
    UserResetPasswordView,
    UserUpdateView,
)

app_name = "users"
urlpatterns = [
    path(
        "~first_connect/",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path(
        "~first_connect/<str:page>",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="update"),
    path(
        "~update/client",
        view=UserClientUpdateView.as_view(),
        name="update_client",
    ),
    path("~security/", view=UserUpdateView.as_view(), name="security"),
    path(
        "reset_password/",
        view=UserResetPasswordView.as_view(),
        name="reset_password",
    ),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views

urlpatterns = [
    re_path(
        r"^accounts/.*email/",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path("", include("chat.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("chat.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("guild/", include("chat.apps.guilds.urls", namespace="guild")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket
    # development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

chat/apps/guilds/features/channels/forms.py
from django import forms
from django.core.exceptions import ValidationError
from rich import inspect

from .models import Message


class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = Message

        fields = ["author", "channel", "recipient", "content", "nonce"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cd = self.cleaned_data | self.initial

        channel = cd.get("channel")
        author = cd.get("author")

        if not all((channel, author)):
            raise ValidationError("Internal values not passed")

        if not author.can_see(channel):
            raise ValidationError("Unknown channel for user")

        return cd

chat/apps/guilds/features/channels/views.py
import uuid
from typing import Any, Dict

from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from .models import Channel
from ...models import Guild
from ...utils import get_guild
from ...views import BaseGuildView, template_path
from .mixins import ChanExistsMixin

template_path += "channels/"


def get_params(request: ASGIRequest, guild_id: uuid.UUID) -> Dict[str, Any]:
    guilds = Guild.objects.filter(members__in=[request.user])
    guild = get_guild(guild_id)

    return {"guild": guild, "guilds": guilds}


class BaseChannelView(BaseGuildView, ChanExistsMixin):
    pass


# =============================================================================


class GuildChannelCreateView(BaseChannelView):
    template_name = template_path + "create.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelEditView(BaseChannelView):
    template_name = template_path + "edit.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelDetailView(BaseChannelView):
    template_name = template_path + "details.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> HttpResponse:
        params = get_params(request, guild_id)
        guild: Guild = params["guild"]

        channel: Channel = guild.channels.get(id__exact=channel_id)

        if not channel:
            return redirect("guild:guild_details", guild_id=str(guild_id))

        params["room_name"] = channel
        params["room_messages"] = channel.get_messages(request.user)

        return render(request, self.template_name, params)

    # =========================================================================

    def post(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> JsonResponse:
        result = {}  # type: ignore

        return JsonResponse(result)

chat/apps/guilds/features/invites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.asgi import ASGIRequest
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext as _
from django.views import View

from ...views import template_path
from .mixins import OwnsInvitationMixin
from .models import Invite

template_path += "invite/"


class GuildJoinInviteView(LoginRequiredMixin, View):
    def get(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        # pylint: disable=superfluous-parens
        if not (invite := Invite.objects.filter(key=invite_key).first()):
            raise Http404()

        guild = invite.guild

        if request.user in guild.members.all():
            return redirect("guild:guild_details", guild_id=guild.id)

        invite.uses += 1
        guild.members.add(self.request.user)
        guild.save()
        invite.save()

        messages.add_message(
            request, messages.INFO, _("Guild joined successfully")
        )

        return redirect("guild:guild_details", guild_id=guild.id)


# =============================================================================


class GuildDeleteInviteView(OwnsInvitationMixin, View):
    # noinspection PyMethodMayBeStatic
    def post(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        query = Q(author=request.user)
        query.add(Q(guild__owner=request.user), Q.OR)
        query.add(Q(key=invite_key), Q.AND)

        if invite := Invite.objects.filter(query).first():
            guild_id = invite.guild.id

            invite.delete()
            messages.add_message(
                request, messages.SUCCESS, _("Invitation deleted successfully")
            )

            return redirect("guild:guild_details", guild_id=guild_id)

        raise Http404()

chat/apps/users/views.py
from allauth.account.utils import user_pk_to_url_str
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, RedirectView
from faker import Faker

from .forms import (
    ResetPasswordForm,
    UserClientUpdateProcessAction,
    UserSettingsForm,
)

User = get_user_model()
template_path = "users/"

locales = {}
for lang_key, lang_name in settings.LANGUAGES:
    locales[lang_key] = lang_name

fake = Faker(list(locales.keys()))


class BaseUsersView(LoginRequiredMixin):
    pass


# =============================================================================


class UserDetailView(BaseUsersView, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


# =============================================================================


class UserRedirectView(BaseUsersView, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}  # type: ignore
        )


# =============================================================================


class UserUpdateView(BaseUsersView, View):
    template_name = template_path + "settings.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(instance=request.user.settings)  # type: ignore

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(
            request.POST,
            request.FILES,
            instance=request.user.settings,  # type: ignore
        )

        if form.is_valid():
            form.save()

            messages.add_message(
                request,
                messages.SUCCESS,
                _("Information updated successfully"),
            )

            return redirect("users:redirect")

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserClientUpdateView(BaseUsersView, View):
    # noinspection PyMethodMayBeStatic
    def patch(self, request: ASGIRequest) -> JsonResponse:
        return UserClientUpdateProcessAction(request).response()


# =============================================================================


class UserResetPasswordView(View):
    template_name = template_path + "reset_password.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm()

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            return redirect(
                "account_reset_password_from_key",
                uidb36=user_pk_to_url_str(form.user),
                key=default_token_generator.make_token(form.user),
            )

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserFistConnectView(BaseUsersView, View):
    template_name = template_path + "first_connect"

    def get(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if (
            user_settings := User.objects.get(id=request.user.id)  # type: ignore
        ) and not user_settings.first_connect:
            return redirect("users:redirect")

        if page == "first":
            return render(request, self.template_name + "/first.html")

        if page == "next":
            mnemonics = {
                locale: " ".join(fake[k].words(nb=10))  # type: ignore
                for k, locale in locales.items()
            }

            request.session["mnemonics"] = mnemonics

            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        return redirect("users:first_connect")

    def post(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if page != "next":
            return redirect("users:first_connect")

        mnemonic = request.POST.get("mnemonic")
        public_key = request.POST.get("public_key")
        mnemonics = request.session["mnemonics"]

        if mnemonic not in mnemonics.values():
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit proposed mnemonics"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )
        if not public_key:
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit autofilled inputs"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        del request.session["mnemonics"]

        user = User.objects.get(id=request.user.id)  # type: ignore
        user.mnemonic = make_password(mnemonic)
        user.public_key = public_key
        user.first_connect = False
        user.save()

        messages.add_message(
            request,
            messages.INFO,
            f'"{mnemonic}" '
            + _(
                "has been set as your mnemonic, remember not to lose it under "
                "any circumstances!"
            ),
        )

        return redirect("users:detail", username=request.user.username)  # type: ignore

chat/templates/guild/settings/members.html
{% extends "layouts/base.html" %}
{% load debug %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load guilds %}

{% block title %}{{ guild.name }} | {% trans "Members" %} - {{ APP_NAME }}{% endblock %}

{% block content %}
    <div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>
        <div class="uk-width-1-1@m">
            <div class="uk-margin uk-width-1 uk-margin-auto uk-card uk-card-default">
                <div class="uk-card-header">
                    <ul class="uk-breadcrumb uk-margin-remove-bottom">
                        <li><a href="{% url "guild:home" %}">Guilds</a></li>
                        <li><a href="{% url "guild:guild_details" guild.id %}">{{ guild.name }}</a></li>
                        <li><a href="{% url "guild:guild_settings" guild.id %}">{% trans "Settings" %}</a></li>
                        <li><span>{% trans "Members" %}</span></li>
                    </ul>
                </div>

                <div class="uk-card-body">
                    <h1 class="uk-card-title uk-text-center">
                        {% trans "Members" %}
                    </h1>

                    <form action="{% url 'guild:guild_settings_members' guild.id %}" method="post">
                        {% csrf_token %}

                        <div class="uk-overflow-auto uk-margin-bottom">
                            <table class="uk-table uk-table-striped">
                                <caption>{{ guild.members_count }} {% trans 'members' %}</caption>
                                <thead>
                                <tr>
                                    <th scope="col" class="uk-table-shrink"></th>
                                    <th scope="col" class="uk-table-expand">{% trans "Name" %}</th>
                                    <th scope="col" class="uk-width-medium">{% trans "Messages sent" %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for member in form.members.initial %}
                                    <tr>
                                        <td>
                                            <input id="user_checkbox_{{ member.id }}" type="checkbox"
                                                   name="{{ form.members.name }}[{{ member.id }}]"
                                                   {% if member == request.user %}disabled{% endif %}>
                                        </td>
                                        <td>
                                            <label for="user_checkbox_{{ member.id }}">
                                                <a href="{% url 'users:detail' member %}" target="_blank">
                                                    {{ member }}
                                                    {% if member == request.user %}
                                                        <i class="uk-text-muted">({% trans "you" %})</i>
                                                    {% endif %}
                                                </a>
                                            </label>
                                        </td>
                                        <td>
                                            <label for="user_checkbox_{{ member.id }}">
                                                {{ member|get_messages_sent:guild|length }}
                                            </label>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if form.members.errors %}
                                <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                                    {% for error in form.members.errors %}
                                        <li class="uk-text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {% if form.action.errors %}
                                <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                                    {% for error in form.action.errors %}
                                        <li class="uk-text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="uk-margin uk-flex uk-flex-between">
                            <div class="uk-button-group">
                                <button class="uk-button uk-button-primary" type="submit" value="kick"
                                        name="{{ form.action.name }}">
                                    {% trans 'Kick' %}
                                </button>
                                <button class="uk-button uk-button-danger" type="submit" value="ban"
                                        name="{{ form.action.name }}">
                                    {% trans 'Ban' %} (disabled)
                                </button>
                            </div>

                            <a class="uk-button uk-button-default" href="{% url 'guild:guild_settings' guild.id %}">
                                {% trans "Back" %}
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

chat/templates/guild/settings/settings.html
{% extends "layouts/base.html" %}
{% load debug %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ guild.name }} | {% trans "Settings" %} - {{ APP_NAME }}{% endblock %}


{% block content %}
    <div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>
        <div class="uk-width-1-1@m">
            <div class="uk-margin uk-width-1 uk-margin-auto uk-card uk-card-default">
                <div class="uk-card-body">
                    <div class="uk-text-center">
                        <img src="{{ guild.avatar.url }}" alt="Avatar">
                        <h1 class="uk-card-title uk-text-center">
                            {{ guild.name }}
                        </h1>
                    </div>

                    <form class="uk-grid" uk-grid method="post" action="{% url 'guild:guild_settings' guild.id %}"
                          enctype="multipart/form-data">
                        {% csrf_token %}

                        {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}"
                                   value="{{ redirect_field_value }}"/>
                        {% endif %}

                        {% if form.non_field_errors %}
                            <div class="uk-alert uk-alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="uk-margin uk-width-1-2">
                            <label class="uk-form-label" for="{{ form.name.id_for_label }}">
                                {{ form.name.label }}
                                {% if form.name.help_text %}
                                    <span class="uk-text-muted">({{ form.name.help_text }})</span>
                                {% endif %}
                            </label>
                            <div class="uk-form-controls">
                                <input class="uk-input {% if form.name.errors %}uk-form-danger{% endif %}"
                                       type="{{ form.name.widget_type }}" required
                                       value="{{ form.name.initial }}"
                                       id="{{ form.name.id_for_label }}" name="{{ form.name.name }}"
                                       placeholder="{% trans 'name' %}">

                                {% if form.name.errors %}
                                    <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                                        {% for error in form.name.errors %}
                                            <li class="uk-text-danger">{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>

                        <div class="uk-margin uk-width-1-2" uk-form-custom="target: true">
                            <label class="uk-form-label" for="{{ form.avatar.id_for_label }}">
                                {{ form.avatar.label }}
                                {% if form.avatar.help_text %}
                                    <span class="uk-text-muted">({{ form.avatar.help_text }})</span>
                                {% endif %}
                            </label>
                            <input type="file" name="{{ form.avatar.name }}">
                            <input class="uk-input {% if form.avatar.errors %}uk-form-danger{% endif %}" type="text"
                                   placeholder="{% trans 'Choose an avatar' %}" id="{{ form.avatar.id_for_label }}"
                                   disabled>

                            {% if form.avatar.errors %}
                                <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                                    {% for error in form.avatar.errors %}
                                        <li class="uk-text-danger">{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="uk-margin uk-width-1-3@s">
                            <label class="uk-form-label">
                                {% trans "Members" %}
                            </label>
                            <div class="uk-form-controls">
                                <a href="{% url 'guild:guild_settings_members' guild.id %}"
                                   class="uk-width-1-1 uk-button uk-button-default">{% trans "Kick/ban members" %}</a>
                            </div>
                        </div>

                        <div class="uk-margin uk-width-1-3@s">
                            <label class="uk-form-label">
                                {% trans "Channels" %}
                            </label>
                            <div class="uk-form-controls">
                                <a href="{% url 'guild:guild_settings_channels' guild.id %}"
                                   class="uk-width-1-1 uk-button uk-button-default">{% trans "Manage channels" %}</a>
                            </div>
                        </div>

                        <div class="uk-margin uk-width-1-3@s">
                            <label class="uk-form-label">
                                {% trans "Invites" %}
                            </label>
                            <div class="uk-form-controls">
                                <a href="{% url 'guild:guild_invites' guild.id %}"
                                   class="uk-width-1-1 uk-button uk-button-default">{% trans "Manage invites" %}</a>
                            </div>
                        </div>

                        <div class="uk-margin uk-width-1-1 uk-flex uk-flex-between">
                            <button class="uk-button uk-button-primary" name="action_add">
                                {% trans "Save" %}
                            </button>
                            <a class="uk-button uk-button-default" href="{% url 'guild:guild_details' guild.id %}">
                                {% trans "Back" %}
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}