chat/apps/guilds/urls.py
from django.urls import path

from .features.channels.urls import urlpatterns as channels_routes
from .features.invites.urls import urlpatterns as invites_routes
from .views import (
    GuildCreateView,
    GuildDetailView,
    GuildHomeView,
    GuildInvitesView,
    GuildJoinView,
    GuildSettingsChannelsView,
    GuildSettingsHomeView,
    GuildSettingsMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path("join/", view=GuildJoinView.as_view(), name="join"),
]

# Guild routes
urlpatterns += [
    path(
        "<uuid:guild_id>/",
        view=GuildDetailView.as_view(),
        name="guild_details",
    ),
    path(
        "<uuid:guild_id>/invites/",
        view=GuildInvitesView.as_view(),
        name="guild_invites",
    ),
    path(
        "<uuid:guild_id>/settings/",
        view=GuildSettingsHomeView.as_view(),
        name="guild_settings",
    ),
    path(
        "<uuid:guild_id>/settings/members/",
        view=GuildSettingsMembersView.as_view(),
        name="guild_settings_members",
    ),
    path(
        "<uuid:guild_id>/settings/channels/",
        view=GuildSettingsChannelsView.as_view(),
        name="guild_settings_channels",
    ),
]

# Channel routes
urlpatterns += channels_routes

# Invite routes
urlpatterns += invites_routes

chat/guild/urls.py
from django.urls import path

from .views import (
    GuildHomeView,
    GuildDetailView,
    GuildCreateView,
    GuildInviteView,
    GuildDeleteInviteView,
    GuildMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path(
        "<int:guild_id>/invite/", view=GuildInviteView.as_view(), name="invite"
    ),
    path(
        "<uuid:guild_id>/members/",
        view=GuildMembersView.as_view(),
        name="members",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>",
        view=GuildInviteView.as_view(),
        name="invite_join",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>/delete",
        view=GuildDeleteInviteView.as_view(),
        name="invite_delete",
    ),
    path("<uuid:guild_id>/", view=GuildDetailView.as_view(), name="detail"),
]

chat/pages/urls.py
from django.urls import path

from chat.pages.views import HomeView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
]

chat/users/urls.py
from django.urls import path

from chat.users.views import (
    UserClientUpdateView,
    UserDetailView,
    UserFistConnectView,
    UserRedirectView,
    UserResetPasswordView,
    UserUpdateView,
)

app_name = "users"
urlpatterns = [
    path(
        "~first_connect/",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path(
        "~first_connect/<str:page>",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="update"),
    path(
        "~update/client",
        view=UserClientUpdateView.as_view(),
        name="update_client",
    ),
    path("~security/", view=UserUpdateView.as_view(), name="security"),
    path(
        "reset_password/",
        view=UserResetPasswordView.as_view(),
        name="reset_password",
    ),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views

urlpatterns = [
    re_path(
        r"^accounts/.*email/",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path("", include("chat.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("chat.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("guild/", include("chat.apps.guilds.urls", namespace="guild")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket
    # development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

chat/apps/guilds/features/channels/forms.py
from django import forms
from django.core.exceptions import ValidationError
from rich import inspect

from .models import Message


class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = Message

        fields = ["author", "channel", "recipient", "content", "nonce"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cd = self.cleaned_data | self.initial

        channel = cd.get("channel")
        author = cd.get("author")

        if not all((channel, author)):
            raise ValidationError("Internal values not passed")

        if not author.can_see(channel):
            raise ValidationError("Unknown channel for user")

        return cd

chat/apps/guilds/features/channels/views.py
import uuid
from typing import Any, Dict

from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from .models import Channel
from ...models import Guild
from ...utils import get_guild
from ...views import BaseGuildView, template_path
from .mixins import ChanExistsMixin

template_path += "channels/"


def get_params(request: ASGIRequest, guild_id: uuid.UUID) -> Dict[str, Any]:
    guilds = Guild.objects.filter(members__in=[request.user])
    guild = get_guild(guild_id)

    return {"guild": guild, "guilds": guilds}


class BaseChannelView(BaseGuildView, ChanExistsMixin):
    pass


# =============================================================================


class GuildChannelCreateView(BaseChannelView):
    template_name = template_path + "create.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelEditView(BaseChannelView):
    template_name = template_path + "edit.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelDetailView(BaseChannelView):
    template_name = template_path + "details.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> HttpResponse:
        params = get_params(request, guild_id)
        guild: Guild = params["guild"]

        channel: Channel = guild.channels.get(id__exact=channel_id)

        if not channel:
            return redirect("guild:guild_details", guild_id=str(guild_id))

        params["room_name"] = channel
        params["room_messages"] = channel.get_messages(request.user)

        return render(request, self.template_name, params)

    # =========================================================================

    def post(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> JsonResponse:
        result = {}  # type: ignore

        return JsonResponse(result)

chat/apps/guilds/features/invites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.asgi import ASGIRequest
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext as _
from django.views import View

from ...views import template_path
from .mixins import OwnsInvitationMixin
from .models import Invite

template_path += "invite/"


class GuildJoinInviteView(LoginRequiredMixin, View):
    def get(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        # pylint: disable=superfluous-parens
        if not (invite := Invite.objects.filter(key=invite_key).first()):
            raise Http404()

        guild = invite.guild

        if request.user in guild.members.all():
            return redirect("guild:guild_details", guild_id=guild.id)

        invite.uses += 1
        guild.members.add(self.request.user)
        guild.save()
        invite.save()

        messages.add_message(
            request, messages.INFO, _("Guild joined successfully")
        )

        return redirect("guild:guild_details", guild_id=guild.id)


# =============================================================================


class GuildDeleteInviteView(OwnsInvitationMixin, View):
    # noinspection PyMethodMayBeStatic
    def post(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        query = Q(author=request.user)
        query.add(Q(guild__owner=request.user), Q.OR)
        query.add(Q(key=invite_key), Q.AND)

        if invite := Invite.objects.filter(query).first():
            guild_id = invite.guild.id

            invite.delete()
            messages.add_message(
                request, messages.SUCCESS, _("Invitation deleted successfully")
            )

            return redirect("guild:guild_details", guild_id=guild_id)

        raise Http404()

chat/apps/users/views.py
from allauth.account.utils import user_pk_to_url_str
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, RedirectView
from faker import Faker

from .forms import (
    ResetPasswordForm,
    UserClientUpdateProcessAction,
    UserSettingsForm,
)

User = get_user_model()
template_path = "users/"

locales = {}
for lang_key, lang_name in settings.LANGUAGES:
    locales[lang_key] = lang_name

fake = Faker(list(locales.keys()))


class BaseUsersView(LoginRequiredMixin):
    pass


# =============================================================================


class UserDetailView(BaseUsersView, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


# =============================================================================


class UserRedirectView(BaseUsersView, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}  # type: ignore
        )


# =============================================================================


class UserUpdateView(BaseUsersView, View):
    template_name = template_path + "settings.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(instance=request.user.settings)  # type: ignore

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(
            request.POST,
            request.FILES,
            instance=request.user.settings,  # type: ignore
        )

        if form.is_valid():
            form.save()

            messages.add_message(
                request,
                messages.SUCCESS,
                _("Information updated successfully"),
            )

            return redirect("users:redirect")

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserClientUpdateView(BaseUsersView, View):
    # noinspection PyMethodMayBeStatic
    def patch(self, request: ASGIRequest) -> JsonResponse:
        return UserClientUpdateProcessAction(request).response()


# =============================================================================


class UserResetPasswordView(View):
    template_name = template_path + "reset_password.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm()

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            return redirect(
                "account_reset_password_from_key",
                uidb36=user_pk_to_url_str(form.user),
                key=default_token_generator.make_token(form.user),
            )

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserFistConnectView(BaseUsersView, View):
    template_name = template_path + "first_connect"

    def get(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if (
            user_settings := User.objects.get(id=request.user.id)  # type: ignore
        ) and not user_settings.first_connect:
            return redirect("users:redirect")

        if page == "first":
            return render(request, self.template_name + "/first.html")

        if page == "next":
            mnemonics = {
                locale: " ".join(fake[k].words(nb=10))  # type: ignore
                for k, locale in locales.items()
            }

            request.session["mnemonics"] = mnemonics

            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        return redirect("users:first_connect")

    def post(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if page != "next":
            return redirect("users:first_connect")

        mnemonic = request.POST.get("mnemonic")
        public_key = request.POST.get("public_key")
        mnemonics = request.session["mnemonics"]

        if mnemonic not in mnemonics.values():
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit proposed mnemonics"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )
        if not public_key:
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit autofilled inputs"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        del request.session["mnemonics"]

        user = User.objects.get(id=request.user.id)  # type: ignore
        user.mnemonic = make_password(mnemonic)
        user.public_key = public_key
        user.first_connect = False
        user.save()

        messages.add_message(
            request,
            messages.INFO,
            f'"{mnemonic}" '
            + _(
                "has been set as your mnemonic, remember not to lose it under "
                "any circumstances!"
            ),
        )

        return redirect("users:detail", username=request.user.username)  # type: ignore

chat/templates/layouts/parts/footer.html
{% load i18n %}
{% load static %}
{% if channel %}
    <div id="footer">
        <form action="" class="height-100">
            <div class="form">
                <div class="inline height-100">
                    <label for="id_upload" class="form-icon">
                        <i class="svg" style="--svg-url: url('{% static "images/icons/image_upload.svg" %}')"></i>
                        <input type="file" multiple aria-label="{% trans "Upload" %}" style="display: none"
                               id="id_upload" name="upload">
                    </label>

                    <label for="id_{{ message_form.name.name }}" class="height-100">
                            <textarea style="resize: none"
                                      class="height-100 input input-icon-right input-icon-left {% if message_form.name.errors %} input-error {% endif %}"
                                      type="text" name="message"
                                      placeholder="{% trans "Message" %} #{{ channel.name }}"
                                      required id="id_{{ message_form.name.name }}"></textarea>
                    </label>

                    <label for="id_send" class="form-icon form-icon-flip">
                        <i class="svg" style="--svg-url: url('{% static "images/icons/paper-plane.svg" %}')"></i>
                        <input type="submit" aria-label="{% trans "Send" %}" style="display: none" id="id_send"
                               name="submit">
                    </label>
                </div>
            </div>
        </form>
    </div>
{% endif %}

chat/templates/layouts/parts/navbar.html
{% load static %}
{% load i18n %}

<nav class="uk-background-secondary" uk-navbar="mode: click">
    <div class="uk-navbar-left">
        <a class="uk-navbar-item uk-logo" href="{% url 'pages:home' %}">
            <img src="{% static 'images/logo.png' %}" alt="C3E">
        </a>
    </div>

    {% if request.user.is_authenticated %}
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li>
                    <a class="uk-text-bold">
                        <span uk-icon="icon: chevron-down">{{ request.user }}</span>
                    </a>
                    <div class="uk-navbar-dropdown uk-border-rounded">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li>
                                <a href="{% url 'users:detail' request.user %}"
                                   class="uk-flex uk-flex-between uk-flex-middle">
                                    <span>{% trans "Profile" %}</span>
                                    <span uk-icon="icon: user"></span>
                                </a>
                            </li>
                            <li class="uk-nav-divider"></li>
                            <li>
                                <a href="{% url 'account_logout' %}" class="uk-flex uk-flex-between uk-flex-middle">
                                    <span>{% trans "Sign Out" %}</span>
                                    <span uk-icon="icon: sign-out"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    {% endif %}
</nav>

chat/templates/layouts/parts/sidebar.html
{% load checks %}
{% load define %}
{% load guilds %}
{% load static %}
{% load compress %}
{% load i18n %}
{% load tags %}


<div class="uk-card-header uk-padding-remove">
    <div class="uk-navbar-container uk-navbar-transparent" uk-navbar="duration: 100; offset: 100px;">
        <div class="uk-navbar-left">
            <a class="uk-navbar-toggle uk-position-relative" uk-toggle="target: #offcanvas-overlay">
                <span uk-navbar-toggle-icon></span>
                <span class="uk-margin-small-left">{% trans "Channels" %}</span>
{#                <span class="uk-badge uk-badge-danger">99+</span>#}
            </a>
        </div>

        {% if room_name %}
            <div class="uk-navbar-center uk-card-title uk-visible@m"
                 uk-tooltip="title: {{ room_name.topic }}; pos: bottom">
                <span uk-icon="icon: hashtag"></span>
                {{ room_name.name }}
            </div>
        {% endif %}

        <div class="uk-navbar-right">
            <div class="uk-grid-small uk-flex-middle uk-margin-right" uk-grid>
                <div class="uk-width-auto">
                    <img class="uk-border-rounded" width="40" height="40" src="{{ guild.avatar.url }}"
                         alt="{{ guild.name }}">
                </div>
                <div class="uk-width-expand">
                    <h3 class="uk-card-title uk-margin-remove-bottom uk-overflow-hidden">
                        <a class="uk-card-title"
                           href="{% url 'guild:guild_details' guild.id %}">{{ guild.name }}</a>
                        {% if guild.owner == request.user %}
                            <a href="{% url 'guild:guild_settings' guild.id %}">
                                <span class="uk-text-middle" uk-icon="icon: cog"></span>
                            </a>
                        {% endif %}
                    </h3>
                    <p class="uk-text-meta uk-margin-remove-top">
                        <span>{{ guild.members_count }} {% trans "members" %}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="offcanvas-overlay" uk-offcanvas="overlay: true">
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>

        <ul class="uk-list">
            {% for row in guild|show_channels_and_categories %}
                <li>
                    {% if not row|isinstance:"chat.apps.guilds.models.Category" %}
                        {% channel_anchor guild row current=current_channel.id %}
                    {% else %}
                        {% collapsed_category category=row member=request.user as collasped %}
                        <a class="uk-nav-header uk-text-muted" uk-toggle="target: .toggle_{{ row.id }};">
                            <span class="toggle_{{ row.id }}" {% if collasped %}hidden{% endif %}
                                  uk-icon="icon: chevron-down"></span>
                            <span class="toggle_{{ row.id }}" {% if not collasped %}hidden{% endif %}
                                  uk-icon="icon: chevron-right"></span>
                            <span>{{ row.name }}</span>
                        </a>

                        <ul class="uk-list uk-margin-left toggle_{{ row.id }}" {% if collasped %}hidden{% endif %}>
                            {% for channel in row|show_channels_from_category %}
                                <li>
                                    {% channel_anchor guild channel current=current_channel.id %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

    <script>
        const UPDATE_CLIENT_ENDPOINT = "{% url "users:update_client" %}";

        function toggle(e) {
            let category_id = Array.from(e.target.classList).filter(cls => {
                return cls.startsWith("toggle_");
            });

            if (category_id.length === 0) return;
            else category_id = category_id[0].slice(7);

            fetch(
                UPDATE_CLIENT_ENDPOINT,
                {
                    method: "PATCH",
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    body: JSON.stringify({
                        action: "collapse_category",
                        values: {
                            category_id: category_id
                        },
                    })
                }
            )
        }

        document.addEventListener("DOMContentLoaded", () => {
            let toggle_id;
            {% for category in guild.categories.all %}
                toggle_id = document.querySelector("ul.toggle_{{ category.id }}");

                toggle_id.addEventListener("hide", toggle);
                toggle_id.addEventListener("show", toggle);
            {% endfor %}
        })
    </script>