chat/guild/urls.py
from django.urls import path

from .views import (
    GuildHomeView,
    GuildDetailView,
    GuildCreateView,
    GuildInviteView,
    GuildDeleteInviteView,
    GuildMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path(
        "<int:guild_id>/invite/", view=GuildInviteView.as_view(), name="invite"
    ),
    path(
        "<uuid:guild_id>/members/",
        view=GuildMembersView.as_view(),
        name="members",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>",
        view=GuildInviteView.as_view(),
        name="invite_join",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>/delete",
        view=GuildDeleteInviteView.as_view(),
        name="invite_delete",
    ),
    path("<uuid:guild_id>/", view=GuildDetailView.as_view(), name="detail"),
]

chat/pages/urls.py
from django.urls import path

from chat.pages.views import HomeView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
]

chat/users/urls.py
from django.urls import path

from chat.users.views import (
    UserClientUpdateView,
    UserDetailView,
    UserFistConnectView,
    UserRedirectView,
    UserResetPasswordView,
    UserUpdateView,
)

app_name = "users"
urlpatterns = [
    path(
        "~first_connect/",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path(
        "~first_connect/<str:page>",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="update"),
    path(
        "~update/client",
        view=UserClientUpdateView.as_view(),
        name="update_client",
    ),
    path("~security/", view=UserUpdateView.as_view(), name="security"),
    path(
        "reset_password/",
        view=UserResetPasswordView.as_view(),
        name="reset_password",
    ),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views

urlpatterns = [
    re_path(
        r"^accounts/.*email/",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path("", include("chat.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("chat.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("guild/", include("chat.apps.guilds.urls", namespace="guild")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket
    # development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

chat/apps/guilds/features/channels/views.py
import uuid
from typing import Any, Dict

from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from .models import Channel
from ...models import Guild
from ...utils import get_guild
from ...views import BaseGuildView, template_path
from .mixins import ChanExistsMixin

template_path += "channels/"


def get_params(request: ASGIRequest, guild_id: uuid.UUID) -> Dict[str, Any]:
    guilds = Guild.objects.filter(members__in=[request.user])
    guild = get_guild(guild_id)

    return {"guild": guild, "guilds": guilds}


class BaseChannelView(BaseGuildView, ChanExistsMixin):
    pass


# =============================================================================


class GuildChannelCreateView(BaseChannelView):
    template_name = template_path + "create.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelEditView(BaseChannelView):
    template_name = template_path + "edit.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelDetailView(BaseChannelView):
    template_name = template_path + "details.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> HttpResponse:
        params = get_params(request, guild_id)
        guild: Guild = params["guild"]

        channel: Channel = guild.channels.get(id__exact=channel_id)

        if not channel:
            return redirect("guild:guild_details", guild_id=str(guild_id))

        params["room_name"] = channel
        params["room_messages"] = channel.get_messages(request.user)

        return render(request, self.template_name, params)

    # =========================================================================

    def post(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> JsonResponse:
        result = {}  # type: ignore

        return JsonResponse(result)

chat/apps/guilds/features/invites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.asgi import ASGIRequest
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext as _
from django.views import View

from ...views import template_path
from .mixins import OwnsInvitationMixin
from .models import Invite

template_path += "invite/"


class GuildJoinInviteView(LoginRequiredMixin, View):
    def get(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        # pylint: disable=superfluous-parens
        if not (invite := Invite.objects.filter(key=invite_key).first()):
            raise Http404()

        guild = invite.guild

        if request.user in guild.members.all():
            return redirect("guild:guild_details", guild_id=guild.id)

        invite.uses += 1
        guild.members.add(self.request.user)
        guild.save()
        invite.save()

        messages.add_message(
            request, messages.INFO, _("Guild joined successfully")
        )

        return redirect("guild:guild_details", guild_id=guild.id)


# =============================================================================


class GuildDeleteInviteView(OwnsInvitationMixin, View):
    # noinspection PyMethodMayBeStatic
    def post(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        query = Q(author=request.user)
        query.add(Q(guild__owner=request.user), Q.OR)
        query.add(Q(key=invite_key), Q.AND)

        if invite := Invite.objects.filter(query).first():
            guild_id = invite.guild.id

            invite.delete()
            messages.add_message(
                request, messages.SUCCESS, _("Invitation deleted successfully")
            )

            return redirect("guild:guild_details", guild_id=guild_id)

        raise Http404()

chat/apps/users/views.py
from allauth.account.utils import user_pk_to_url_str
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, RedirectView
from faker import Faker

from .forms import (
    ResetPasswordForm,
    UserClientUpdateProcessAction,
    UserSettingsForm,
)

User = get_user_model()
template_path = "users/"

locales = {}
for lang_key, lang_name in settings.LANGUAGES:
    locales[lang_key] = lang_name

fake = Faker(list(locales.keys()))


class BaseUsersView(LoginRequiredMixin):
    pass


# =============================================================================


class UserDetailView(BaseUsersView, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


# =============================================================================


class UserRedirectView(BaseUsersView, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}  # type: ignore
        )


# =============================================================================


class UserUpdateView(BaseUsersView, View):
    template_name = template_path + "settings.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(instance=request.user.settings)  # type: ignore

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(
            request.POST,
            request.FILES,
            instance=request.user.settings,  # type: ignore
        )

        if form.is_valid():
            form.save()

            messages.add_message(
                request,
                messages.SUCCESS,
                _("Information updated successfully"),
            )

            return redirect("users:redirect")

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserClientUpdateView(BaseUsersView, View):
    # noinspection PyMethodMayBeStatic
    def patch(self, request: ASGIRequest) -> JsonResponse:
        return UserClientUpdateProcessAction(request).response()


# =============================================================================


class UserResetPasswordView(View):
    template_name = template_path + "reset_password.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm()

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            return redirect(
                "account_reset_password_from_key",
                uidb36=user_pk_to_url_str(form.user),
                key=default_token_generator.make_token(form.user),
            )

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserFistConnectView(BaseUsersView, View):
    template_name = template_path + "first_connect"

    def get(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if (
            user_settings := User.objects.get(id=request.user.id)  # type: ignore
        ) and not user_settings.first_connect:
            return redirect("users:redirect")

        if page == "first":
            return render(request, self.template_name + "/first.html")

        if page == "next":
            mnemonics = {
                locale: " ".join(fake[k].words(nb=10))  # type: ignore
                for k, locale in locales.items()
            }

            request.session["mnemonics"] = mnemonics

            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        return redirect("users:first_connect")

    def post(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if page != "next":
            return redirect("users:first_connect")

        mnemonic = request.POST.get("mnemonic")
        public_key = request.POST.get("public_key")
        mnemonics = request.session["mnemonics"]

        if mnemonic not in mnemonics.values():
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit proposed mnemonics"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )
        if not public_key:
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit autofilled inputs"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        del request.session["mnemonics"]

        user = User.objects.get(id=request.user.id)  # type: ignore
        user.mnemonic = make_password(mnemonic)
        user.public_key = public_key
        user.first_connect = False
        user.save()

        messages.add_message(
            request,
            messages.INFO,
            f'"{mnemonic}" '
            + _(
                "has been set as your mnemonic, remember not to lose it under "
                "any circumstances!"
            ),
        )

        return redirect("users:detail", username=request.user.username)  # type: ignore

chat/guilds/features/channels/views.py
import uuid
from typing import Any, Dict

from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from ...models import Guild
from ...utils import get_guild
from ...views import BaseGuildView, template_path
from .mixins import ChanExistsMixin

template_path += "channels/"


def get_params(request: ASGIRequest, guild_id: uuid.UUID) -> Dict[str, Any]:
    guilds = Guild.objects.filter(members__in=[request.user])
    guild = get_guild(guild_id)

    return {"guild": guild, "guilds": guilds}


class BaseChannelView(BaseGuildView, ChanExistsMixin):
    pass


# =============================================================================


class GuildChannelCreateView(BaseChannelView):
    template_name = template_path + "create.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelEditView(BaseChannelView):
    template_name = template_path + "edit.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelDetailView(BaseChannelView):
    template_name = template_path + "details.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> HttpResponse:
        params = get_params(request, guild_id)
        guild: Guild = params["guild"]

        channel = guild.channels.get(id__exact=channel_id)

        if not channel:
            return redirect("guild:guild_details", guild_id=str(guild_id))

        params["channel"] = channel

        print("pre render")
        return render(request, self.template_name, params)

    # =========================================================================

    def post(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> JsonResponse:
        result = {}

        return JsonResponse(result)

chat/templates/users/reset_password.html
{% extends "layouts/base.html" %}
{% load debug %}
{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

{% block title %}{% translate "Reset Password" %}{% endblock %}

{% block content_class %}
    uk-width-large
{% endblock %}

{% block content %}
    <div class="uk-margin uk-margin-auto uk-card-body">
        <h1 class="uk-card-title uk-text-center">{% translate "Reset Password" %}</h1>

        {% if user.is_authenticated %}
            {% include "account/snippets/already_logged_in.html" %}
        {% endif %}
        <div class="uk-alert uk-alert-primary">
            <p>{% trans "Forgot your password? Enter the mnemonic you were given when you registered below." %}</p>
        </div>

        <form autocomplete="off" method="post" action="{% url "users:reset_password" %}">
            {% csrf_token %}

            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}"
                       value="{{ redirect_field_value }}"/>
            {% endif %}

            {% if form.non_field_errors %}
                <div class="uk-alert uk-alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="uk-margin">
                <label class="uk-inline uk-width-1-1" for="{{ form.username.id_for_label }}">
                    <span class="uk-form-icon" uk-icon="icon: user"></span>
                    <input name="{{ form.username.name }}"
                           class="uk-input uk-form-large
                                                {% if form.username.errors %}uk-form-danger{% endif %}"
                           placeholder="{% trans "Username" %}" type="text"
                           id="{{ form.username.id_for_label }}"
                           required>
                </label>
                {% if form.username.errors %}
                    <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                        {% for error in form.username.errors %}
                            <li class="uk-text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="uk-margin">
                <label class="uk-inline uk-width-1-1" for="{{ form.mnemonic.id_for_label }}">
                    <span class="uk-form-icon" uk-icon="icon: tag"></span>
                    <input name="{{ form.mnemonic.name }}"
                           class="uk-input uk-form-large
                                                {% if form.mnemonic.errors %}uk-form-danger{% endif %}"
                           placeholder="{% trans "Mnemonic" %}" type="text"
                           id="{{ form.mnemonic.id_for_label }}"
                           required>
                </label>
                {% if form.mnemonic.errors %}
                    <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                        {% for error in form.mnemonic.errors %}
                            <li class="uk-text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="uk-margin">
                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1">
                    {% trans "Reset My Password" %}
                </button>
            </div>

            <div class="uk-text-small uk-text-center">
                <a href="{% url 'account_login' %}">{% trans "Login" %}</a>
            </div>
        </form>
    </div>
{% endblock %}

chat/templates/users/settings.html
{% extends "layouts/base.html" %}
{% load debug %}
{% load define %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{% trans "Personal data" %}{% endblock %}

{% block content %}
    <div class="uk-card-body">
        <h1 class="uk-card-title uk-text-center">{% trans "Personal data" %}</h1>

        <form class="uk-grid" uk-grid method="post" action="{% url 'users:update' %}"
              enctype="multipart/form-data">
            {% csrf_token %}

            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}"
                       value="{{ redirect_field_value }}"/>
            {% endif %}

            {% if form.non_field_errors %}
                <div class="uk-alert uk-alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="uk-margin uk-width-1-2">
                <label class="uk-form-label" for="id_username">
                    {% trans "Username" %}
                </label>
                <div class="uk-form-controls">
                    <input class="uk-input" type="text" required disabled
                           value="{{ request.user.username }}"
                           id="id_username" placeholder="{% trans 'Username' %}">
                </div>
            </div>

            <div class="uk-margin uk-width-1-2">
                <label class="uk-form-label" for="id_username">
                    {% trans "Private key" %}
                </label>
                <div class="uk-form-controls">
                    <a class="uk-button uk-button-primary uk-width-expand" id="private_key_export">
                        {% trans "Export/Download" %}
                    </a>
                </div>
            </div>

            <div class="uk-margin uk-width-1-3@s" uk-form-custom="target: true">
                <label class="uk-form-label" for="{{ form.avatar.id_for_label }}">
                    {{ form.avatar.label }}
                    {% if form.avatar.help_text %}
                        <span class="uk-text-muted">({{ form.avatar.help_text }})</span>
                    {% endif %}
                </label>
                <input type="file" name="{{ form.avatar.name }}">
                <input class="uk-input {% if form.avatar.errors %}uk-form-danger{% endif %}" type="text"
                       placeholder="{% trans 'Choose an avatar' %}" id="{{ form.avatar.id_for_label }}"
                       disabled>

                {% if form.avatar.errors %}
                    <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                        {% for error in form.avatar.errors %}
                            <li class="uk-text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="uk-margin uk-width-1-3@s">
                <label class="uk-form-label" for="{{ form.language.id_for_label }}">
                    {{ form.language.label }}
                    {% if form.language.help_text %}
                        <span class="uk-text-muted">({{ form.language.help_text }})</span>
                    {% endif %}
                </label>
                <div class="uk-form-controls">
                    <select class="uk-select {% if form.language.errors %}uk-form-danger{% endif %}"
                            id="{{ form.language.id_for_label }}" name="{{ form.language.name }}">
                        {% for choice in form.language %}
                            <option value="{{ choice.data.value }}"
                                {% if choice.data.selected %}
                                    selected
                                {% endif %}>
                                {{ choice.data.label }}
                            </option>
                        {% endfor %}
                    </select>

                    {% if form.language.errors %}
                        <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                            {% for error in form.language.errors %}
                                <li class="uk-text-danger">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>

            <div class="uk-margin uk-width-1-3@s">
                <label class="uk-form-label" for="{{ form.theme.id_for_label }}">
                    {{ form.theme.label }}
                    {% if form.theme.help_text %}
                        <span class="uk-text-muted">({{ form.theme.help_text }})</span>
                    {% endif %}
                </label>
                <div class="uk-form-controls">
                    <select class="uk-select {% if form.theme.errors %}uk-form-danger{% endif %}"
                            id="{{ form.theme.id_for_label }}" name="{{ form.theme.name }}">
                        {% for choice in form.theme %}
                            <option value="{{ choice.data.value }}"
                                {% if choice.data.selected %}
                                    selected
                                {% endif %}>
                                {{ choice.data.label }}
                            </option>
                        {% endfor %}
                    </select>

                    {% if form.theme.errors %}
                        <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                            {% for error in form.theme.errors %}
                                <li class="uk-text-danger">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>

            <div class="uk-margin uk-width-1-1">
                <label class="uk-form-label" for="{{ form.bio.id_for_label }}">
                    {{ form.bio.label }}
                    {% if form.bio.help_text %}
                        <span class="uk-text-muted">({{ form.bio.help_text }})</span>
                    {% endif %}
                </label>
                <div class="uk-form-controls">
                    {% if form.bio.initial %}
                        {% define form.bio.initial as initial %}
                    {% else %}
                        {% define "" as initial %}
                    {% endif %}

                    <textarea class="uk-textarea {% if form.bio.errors %}uk-form-danger{% endif %}"
                              name="{{ form.bio.name }}" id="{{ form.bio.id_for_label }}"
                              style="resize: vertical"
                              rows="5" placeholder="{% trans 'Bio' %}">{{ initial }}</textarea>

                    {% if form.bio.errors %}
                        <ul class="uk-list uk-margin-remove uk-list-disc uk-list-collapse">
                            {% for error in form.bio.errors %}
                                <li class="uk-text-danger">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>

            <div class="uk-margin uk-width-1-1 uk-flex uk-flex-between">
                <button class="uk-button uk-button-primary" type="submit">
                    {% trans "Save" %}
                </button>
                <a class="uk-button uk-button-default" href="{% url 'users:detail' user %}">
                    {% trans "Back" %}
                </a>
            </div>
        </form>
    </div>

    {% block inline_javascript %}
        <script>
            if (window.keyPair === undefined) {
                window.keyPair = window.sessionStorage.getItem("keySet").split("|");
            }

            const anchor = document.getElementById("private_key_export");
            anchor.setAttribute("href", `data:text/plain;charset=utf-8,${encodeURIComponent(keyPair[1])}`);
            anchor.setAttribute('download', "private_key");
        </script>
    {% endblock inline_javascript %}
{% endblock %}

chat/templates/users/user_detail.html
{% extends "layouts/base.html" %}
{% load debug %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content_class %}
    uk-width-large
{% endblock %}

{% block content %}
    <div class="uk-margin uk-margin-auto">
        {% if object.is_staff %}
            <div class="uk-card-badge uk-label">STAFF</div>
        {% endif %}

        <div class="uk-card-header">
            <div class="uk-grid-small uk-flex-middle" uk-grid>
                <div class="uk-width-auto">
                    <img class="uk-border-rounded" width="40" height="40"
                        {% if object.settings.avatar %}
                         src="{{ object.settings.avatar.url }}"
                        {% else %}
                         src="{% static 'images/icons/circle_user.svg' %}"
                        {% endif %}
                         alt="Avatar">
                </div>
                <div class="uk-width-expand">
                    <h1 class="uk-card-title uk-margin-remove-bottom">{{ object.username }}</h1>
                    <p class="uk-text-meta uk-margin-remove-top">
                        <time datetime="{{ object.date_joined.isoformat }}">{{ object.date_joined }}</time>
                    </p>
                </div>
            </div>
        </div>

        <div class="uk-card-body">
            {% if object.settings.bio %}
                {{ object.settings.bio }}
            {% else %}
                <i>{% trans "No bio provided..." %}</i>
            {% endif %}
        </div>
        {% if object == request.user %}
            <div class="uk-card-footer">
                <a class="uk-width-1-1 uk-button uk-button-default"
                   href="{% url 'users:update' %}" role="button">
                    {% trans 'Edit personal data' %}
                </a>
{#                <a class="uk-width-1-1 uk-button uk-button-default"#}
{#                   href="{% url 'users:security' %}" role="button">#}
{#                    {% trans 'Security' %}#}
{#                </a>#}
            </div>
        {% endif %}
    </div>
{% endblock content %}