chat/apps/guilds/features/channels/urls.py
from django.urls import path

from .views import (  # isort:skip
    GuildChannelCreateView,
    GuildChannelDetailView,
    GuildChannelEditView,
)

urlpatterns = [
    path(
        "<uuid:guild_id>/create/",
        view=GuildChannelCreateView.as_view(),
        name="channel_create",
    ),
    path(
        "<uuid:guild_id>/edit",
        view=GuildChannelEditView.as_view(),
        name="channel_edit",
    ),
    path(
        "<uuid:guild_id>/<uuid:channel_id>/",
        view=GuildChannelDetailView.as_view(),
        name="channel_details",
    ),
]

chat/apps/guilds/urls.py
from django.urls import path

from .features.channels.urls import urlpatterns as channels_routes
from .features.invites.urls import urlpatterns as invites_routes
from .views import (
    GuildCreateView,
    GuildDetailView,
    GuildHomeView,
    GuildInvitesView,
    GuildJoinView,
    GuildSettingsChannelsView,
    GuildSettingsHomeView,
    GuildSettingsMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path("join/", view=GuildJoinView.as_view(), name="join"),
]

# Guild routes
urlpatterns += [
    path(
        "<uuid:guild_id>/",
        view=GuildDetailView.as_view(),
        name="guild_details",
    ),
    path(
        "<uuid:guild_id>/invites/",
        view=GuildInvitesView.as_view(),
        name="guild_invites",
    ),
    path(
        "<uuid:guild_id>/settings/",
        view=GuildSettingsHomeView.as_view(),
        name="guild_settings",
    ),
    path(
        "<uuid:guild_id>/settings/members/",
        view=GuildSettingsMembersView.as_view(),
        name="guild_settings_members",
    ),
    path(
        "<uuid:guild_id>/settings/channels/",
        view=GuildSettingsChannelsView.as_view(),
        name="guild_settings_channels",
    ),
]

# Channel routes
urlpatterns += channels_routes

# Invite routes
urlpatterns += invites_routes

chat/guild/urls.py
from django.urls import path

from .views import (
    GuildHomeView,
    GuildDetailView,
    GuildCreateView,
    GuildInviteView,
    GuildDeleteInviteView,
    GuildMembersView,
)

app_name = "guild"
urlpatterns = [
    path("", view=GuildHomeView.as_view(), name="home"),
    path("create/", view=GuildCreateView.as_view(), name="create"),
    path(
        "<int:guild_id>/invite/", view=GuildInviteView.as_view(), name="invite"
    ),
    path(
        "<uuid:guild_id>/members/",
        view=GuildMembersView.as_view(),
        name="members",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>",
        view=GuildInviteView.as_view(),
        name="invite_join",
    ),
    path(
        "<uuid:guild_id>/invite/<str:key>/delete",
        view=GuildDeleteInviteView.as_view(),
        name="invite_delete",
    ),
    path("<uuid:guild_id>/", view=GuildDetailView.as_view(), name="detail"),
]

chat/pages/urls.py
from django.urls import path

from chat.pages.views import HomeView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
]

chat/users/urls.py
from django.urls import path

from chat.users.views import (
    UserClientUpdateView,
    UserDetailView,
    UserFistConnectView,
    UserRedirectView,
    UserResetPasswordView,
    UserUpdateView,
)

app_name = "users"
urlpatterns = [
    path(
        "~first_connect/",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path(
        "~first_connect/<str:page>",
        view=UserFistConnectView.as_view(),
        name="first_connect",
    ),
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="update"),
    path(
        "~update/client",
        view=UserClientUpdateView.as_view(),
        name="update_client",
    ),
    path("~security/", view=UserUpdateView.as_view(), name="security"),
    path(
        "reset_password/",
        view=UserResetPasswordView.as_view(),
        name="reset_password",
    ),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views

urlpatterns = [
    re_path(
        r"^accounts/.*email/",
        default_views.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path("", include("chat.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("chat.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("guild/", include("chat.apps.guilds.urls", namespace="guild")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket
    # development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

chat/apps/guilds/features/channels/forms.py
from django import forms
from django.core.exceptions import ValidationError
from rich import inspect

from .models import Message


class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = Message

        fields = ["author", "channel", "recipient", "content", "nonce"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cd = self.cleaned_data | self.initial

        channel = cd.get("channel")
        author = cd.get("author")

        if not all((channel, author)):
            raise ValidationError("Internal values not passed")

        if not author.can_see(channel):
            raise ValidationError("Unknown channel for user")

        return cd

chat/apps/guilds/features/channels/views.py
import uuid
from typing import Any, Dict

from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from .models import Channel
from ...models import Guild
from ...utils import get_guild
from ...views import BaseGuildView, template_path
from .mixins import ChanExistsMixin

template_path += "channels/"


def get_params(request: ASGIRequest, guild_id: uuid.UUID) -> Dict[str, Any]:
    guilds = Guild.objects.filter(members__in=[request.user])
    guild = get_guild(guild_id)

    return {"guild": guild, "guilds": guilds}


class BaseChannelView(BaseGuildView, ChanExistsMixin):
    pass


# =============================================================================


class GuildChannelCreateView(BaseChannelView):
    template_name = template_path + "create.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelEditView(BaseChannelView):
    template_name = template_path + "edit.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
    ) -> HttpResponse:
        return render(
            request, self.template_name, get_params(request, guild_id)
        )


# =============================================================================


class GuildChannelDetailView(BaseChannelView):
    template_name = template_path + "details.html"

    def get(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> HttpResponse:
        params = get_params(request, guild_id)
        guild: Guild = params["guild"]

        channel: Channel = guild.channels.get(id__exact=channel_id)

        if not channel:
            return redirect("guild:guild_details", guild_id=str(guild_id))

        params["room_name"] = channel
        params["room_messages"] = channel.get_messages(request.user)

        return render(request, self.template_name, params)

    # =========================================================================

    def post(
        self,
        request: ASGIRequest,
        guild_id: uuid.UUID,
        channel_id: uuid.UUID,
    ) -> JsonResponse:
        result = {}  # type: ignore

        return JsonResponse(result)

chat/apps/guilds/features/invites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.asgi import ASGIRequest
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext as _
from django.views import View

from ...views import template_path
from .mixins import OwnsInvitationMixin
from .models import Invite

template_path += "invite/"


class GuildJoinInviteView(LoginRequiredMixin, View):
    def get(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        # pylint: disable=superfluous-parens
        if not (invite := Invite.objects.filter(key=invite_key).first()):
            raise Http404()

        guild = invite.guild

        if request.user in guild.members.all():
            return redirect("guild:guild_details", guild_id=guild.id)

        invite.uses += 1
        guild.members.add(self.request.user)
        guild.save()
        invite.save()

        messages.add_message(
            request, messages.INFO, _("Guild joined successfully")
        )

        return redirect("guild:guild_details", guild_id=guild.id)


# =============================================================================


class GuildDeleteInviteView(OwnsInvitationMixin, View):
    # noinspection PyMethodMayBeStatic
    def post(self, request: ASGIRequest, invite_key: str) -> HttpResponse:
        query = Q(author=request.user)
        query.add(Q(guild__owner=request.user), Q.OR)
        query.add(Q(key=invite_key), Q.AND)

        if invite := Invite.objects.filter(query).first():
            guild_id = invite.guild.id

            invite.delete()
            messages.add_message(
                request, messages.SUCCESS, _("Invitation deleted successfully")
            )

            return redirect("guild:guild_details", guild_id=guild_id)

        raise Http404()

chat/apps/users/views.py
from allauth.account.utils import user_pk_to_url_str
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, RedirectView
from faker import Faker

from .forms import (
    ResetPasswordForm,
    UserClientUpdateProcessAction,
    UserSettingsForm,
)

User = get_user_model()
template_path = "users/"

locales = {}
for lang_key, lang_name in settings.LANGUAGES:
    locales[lang_key] = lang_name

fake = Faker(list(locales.keys()))


class BaseUsersView(LoginRequiredMixin):
    pass


# =============================================================================


class UserDetailView(BaseUsersView, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


# =============================================================================


class UserRedirectView(BaseUsersView, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}  # type: ignore
        )


# =============================================================================


class UserUpdateView(BaseUsersView, View):
    template_name = template_path + "settings.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(instance=request.user.settings)  # type: ignore

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = UserSettingsForm(
            request.POST,
            request.FILES,
            instance=request.user.settings,  # type: ignore
        )

        if form.is_valid():
            form.save()

            messages.add_message(
                request,
                messages.SUCCESS,
                _("Information updated successfully"),
            )

            return redirect("users:redirect")

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserClientUpdateView(BaseUsersView, View):
    # noinspection PyMethodMayBeStatic
    def patch(self, request: ASGIRequest) -> JsonResponse:
        return UserClientUpdateProcessAction(request).response()


# =============================================================================


class UserResetPasswordView(View):
    template_name = template_path + "reset_password.html"

    def get(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm()

        return render(request, self.template_name, {"form": form})

    def post(self, request: ASGIRequest) -> HttpResponse:
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            return redirect(
                "account_reset_password_from_key",
                uidb36=user_pk_to_url_str(form.user),
                key=default_token_generator.make_token(form.user),
            )

        return render(request, self.template_name, {"form": form})


# =============================================================================


class UserFistConnectView(BaseUsersView, View):
    template_name = template_path + "first_connect"

    def get(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if (
            user_settings := User.objects.get(id=request.user.id)  # type: ignore
        ) and not user_settings.first_connect:
            return redirect("users:redirect")

        if page == "first":
            return render(request, self.template_name + "/first.html")

        if page == "next":
            mnemonics = {
                locale: " ".join(fake[k].words(nb=10))  # type: ignore
                for k, locale in locales.items()
            }

            request.session["mnemonics"] = mnemonics

            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        return redirect("users:first_connect")

    def post(self, request: ASGIRequest, page: str = "first") -> HttpResponse:
        if page != "next":
            return redirect("users:first_connect")

        mnemonic = request.POST.get("mnemonic")
        public_key = request.POST.get("public_key")
        mnemonics = request.session["mnemonics"]

        if mnemonic not in mnemonics.values():
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit proposed mnemonics"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )
        if not public_key:
            messages.add_message(
                request,
                messages.WARNING,
                _("Please do not edit autofilled inputs"),
            )
            return render(
                request,
                self.template_name + "/next.html",
                {"mnemonics": mnemonics},
            )

        del request.session["mnemonics"]

        user = User.objects.get(id=request.user.id)  # type: ignore
        user.mnemonic = make_password(mnemonic)
        user.public_key = public_key
        user.first_connect = False
        user.save()

        messages.add_message(
            request,
            messages.INFO,
            f'"{mnemonic}" '
            + _(
                "has been set as your mnemonic, remember not to lose it under "
                "any circumstances!"
            ),
        )

        return redirect("users:detail", username=request.user.username)  # type: ignore

chat/templates/guild/create.html
{% extends "layouts/base.html" %}
{% load static %}
{% load i18n %}
{% load account %}

{% block title %}{{ APP_NAME }} - {% trans 'Create' %}{% endblock %}

{% block content_class %}
    uk-width-large
{% endblock %}

{% block content %}
    <div class="uk-margin uk-margin-auto uk-card-body">
        <h1 class="uk-card-title uk-text-center">{% trans "Create a guild" %}</h1>

        <form autocomplete="off" method="post" action="{% url 'guild:create' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
            {% endif %}

            {% if form.non_field_errors %}
                <div class="uk-alert uk-alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="uk-margin">
                <label class="uk-inline uk-flex uk-flex-center uk-width-1-1" for="id_{{ form.avatar.name }}"
                       uk-form-custom>
                    <input type="file" name="{{ form.avatar.name }}">
                    <button
                        class="uk-button uk-button-default {% if form.avatar.errors %} uk-button-danger {% endif %}"
                        type="button" tabindex="-1">
                        <span uk-icon="icon: camera"></span>
                    </button>
                </label>
            </div>

            <div class="uk-margin">
                <label class="uk-inline uk-width-1-1" for="id_{{ form.name.name }}">
                    <span class="uk-form-icon" uk-icon="icon: hashtag"></span>
                    <input name="{{ form.name.name }}"
                           class="uk-input uk-form-large
                                                    {% if form.name.errors %}uk-form-danger{% endif %}"
                           placeholder="{% trans "Guild name" %}" type="text"
                           id="id_{{ form.name.name }}"
                           required>
                </label>
            </div>

            <div class="uk-margin">
                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1">
                    {% trans "Create" %}
                </button>
            </div>

            <div class="uk-text-small uk-text-center">
                <a class="link icon-right" href="{% url 'guild:join' %}">
                    {% trans "The group is already created? Then please join in by following its invitation link." %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

chat/templates/guild/details.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block title %}{{ guild.name }} - {{ APP_NAME }}{% endblock %}

{% block content %}
    <div class="uk-card-body" uk-height-viewport="offset-top: true; offset-bottom: true">
        <div class="uk-overflow-auto">
            <table id="guildDetails" aria-label="messages" class="uk-table">
                <thead>
                <tr>
                    <th scope="col" class="uk-width-auto">{% trans "Channel" %}</th>
                </tr>
                </thead>
                <tbody>
                {% if latest_channels %}
                    {% for channel in latest_channels %}
                        <tr>
                            <td>
                                <a class="uk-link"
                                href="{% url 'guild:channel_details' guild.id channel.id %}">{{ channel }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="3">{% trans "No result..." %}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

chat/templates/guild/home.html
{% extends "layouts/base.html" %}
{% load static %}
{% load good_morning %}
{% load i18n %}

{% block content_header %}
    <div class="uk-card-header uk-text-center">
        <img class="uk-border-rounded" width="128" height="128"
            {% if user.settings.avatar %}
             src="{{ user.settings.avatar.url }}"
            {% else %}
             src="{% static 'images/icons/circle_user.svg' %}"
            {% endif %}
             alt="Avatar">
        <h1 class="uk-card-title uk-text-bold">
            {{ user.username|good_morning }}
        </h1>
        <a class="uk-text-bold" href="{% url 'users:detail' user %}">
            <span>{% trans "Account Settings" %}</span>
            <span uk-icon="icon: chevron-right"></span>
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="uk-card-body">
        <div class="uk-flex-center uk-grid-match uk-text-center uk-flex-bottom" uk-grid>
            {% for guild in guilds %}
                <a href="{% url "guild:guild_details" guild.id %}">
                    <div uk-tooltip="{{ guild.name }}" class="uk-card">
                        <div class="uk-card-body uk-flex uk-flex-column uk-flex-middle uk-padding-remove-vertical">
                            <img class="uk-border-rounded" loading="lazy"
                                 width="69" height="69" alt="{{ guild.name }} Icon"
                                 src="{{ guild.avatar.url }}">
                            <span>{{ guild.name }}</span>
                        </div>
                    </div>
                </a>
            {% endfor %}

            <a title="{% trans 'Create guild' %}" href="{% url 'guild:create' %}"
               aria-label="{% trans "Create guild" %}">
                <div uk-tooltip="{% trans 'Create guild' %}" class="uk-card">
                    <div class="uk-card-body uk-flex uk-flex-column uk-padding-remove-vertical">
                        <img class="uk-border-circle" loading="lazy"
                             width="69" height="69" alt="{{ guild.name }} Icon"
                             src="{% static "images/icons/circle_plus.svg" %}">
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock content %}

chat/templates/guild/invites.html
{% extends "layouts/base.html" %}
{% load static %}
{% load abs_url %}
{% load qr_generator %}
{% load i18n %}

{% block title %}{{ APP_NAME }} - {% trans 'Invite' %}{% endblock %}

{% block breadcrumb %}
    <ul class="uk-breadcrumb">
        <li>
            <a href="{% url 'guild:home' %}">{% trans "Groups" %}</a>
        </li>
        <li>
            <a href="{% url 'guild:detail' invite.group.uuid %}">{{ invite.group.name }}</a>
        </li>
        <li>
            <span>{% trans "Invite" %}</span>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form class="flex flex-column justify-center align-center height-100 text-center" autocomplete="off" method="post"
          action="{% url "guild:invite_delete" invite.key %}">
        {% csrf_token %}

        <div class="form form-medium margin">
            <a target="_blank" href="{{ invite|generate_qr_code }}" class="form-logo form-logo-large"
               download="{{ invite.guild.name }}_invite.png">
                <img src="{{ invite|generate_qr_code }}" alt="{{ invite.guild.name }} QR">
            </a>

            <fieldset class="fieldset">
                <legend class="legend h1">{{ invite.guild.name }}{% trans "'s invite" %}
                    ({% trans "Uses:" %} {{ invite.uses }})
                </legend>

                <div class="form-progressive">
                    <div class="inline">
                        <label for="id_invite">
                            <input class="input" type="text" id="id_invite" value="{{ invite.key_url|abs_url }}">
                        </label>
                    </div>
                </div>

                {% if invite.guild.owner == request.user %}
                    <div class="margin form-separator"></div>

                    <div class="margin">
                        <button type="submit" class="link button-link text-danger" href="{% url "guild:home" %}">
                            {% trans "Delete" %}
                        </button>
                    </div>
                {% endif %}
            </fieldset>
        </div>
    </form>

{% endblock %}

chat/templates/guild/join.html
{% extends "layouts/base.html" %}
{% load static %}
{% load abs_url %}
{% load qr_generator %}
{% load i18n %}

{% block title %}{{ APP_NAME }} - {% trans 'Join' %}{% endblock %}


{% block content_class %}
    uk-width-large
{% endblock %}

{% block content %}
    <div class="uk-margin uk-margin-auto uk-card-body">
        <h1 class="uk-card-title uk-text-center">{% trans "Join a guild" %}</h1>

        <form autocomplete="off" method="post" autocomplete="off" method="post" action="{% url 'guild:join' %}">
            {% csrf_token %}

            {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
            {% endif %}

            {% if form.non_field_errors %}
                <div class="uk-alert uk-alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="uk-margin">
                <label class="uk-inline uk-width-1-1" for="id_invite">
                    <span class="uk-form-icon" uk-icon="icon: link"></span>
                    <input class="uk-input uk-form-large" type="text" name="invite_key"
                           placeholder="{{ "/invite/hi"|abs_url }}"
                           required id="id_invite">
                </label>
            </div>

            <div class="uk-margin">
                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1">
                    {% trans "Join" %}
                </button>
            </div>

            <div class="uk-text-small uk-text-center">
                <a class="link icon-right" href="{% url 'guild:create' %}">
                    {% trans "The group is not created? Then please create it in by following this link." %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

chat/templates/guild/join_invite.html
{% extends "layouts/base.html" %}
{% load static %}
{% load abs_url %}
{% load qr_generator %}
{% load i18n %}

{% block title %}{{ APP_NAME }} - {% trans 'Invite' %}{% endblock %}

{% block breadcrumb %}
    <ul class="uk-breadcrumb">
        <li>
            <a href="{% url 'guild:home' %}">{% trans "Groups" %}</a>
        </li>
        <li>
            <a href="{% url 'guild:detail' invite.group.uuid %}">{{ invite.group.name }}</a>
        </li>
        <li>
            <span>{% trans "Invite" %}</span>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form class="flex flex-column justify-center align-center height-100 text-center" autocomplete="off" method="post"
          action="{% url "guild:invite_empty_join" %}">
        {% csrf_token %}

        <div class="form form-medium margin">
            <img class="form-logo" src="{% static "images/icons/circle_plus.svg" %}" alt="Plus Icon">

            <fieldset class="fieldset">
                <legend class="legend h1">{% trans "Join a guild" %}</legend>

                <div class="form-progressive">
                    <div class="inline">
                        <label for="id_invite">
                            <input class="input input-icon-right" type="text" name="invite_key"
                                   placeholder="{{ "/invite/hi"|abs_url }}"
                                   required id="id_invite">
                        </label>

                        <button type="submit" class="form-icon form-icon-flip" aria-label="{% trans "Create" %}">
                            <img src="{% static "images/icons/circle_login.svg" %}" alt="+">
                        </button>
                    </div>
                </div>

                <div class="margin form-separator"></div>

                <div class="margin">
                    <a class="link" href="{% url "guild:create" %}">
                        <span>{% trans "The group is not created? Then please create it in by following this link." %}</span>
                    </a>
                </div>
            </fieldset>
        </div>
    </form>

{% endblock %}